package request

const (
	UrlTokenClickId           = "{clickid}"
	UrlTokenCampaignId        = "{campaign.id}"
	UrlTokenTrafficSourceId   = "{trafficsource.id}"
	UrlTokenTrafficSourceName = "{trafficsource.name}"
	UrlTokenDevice            = "{device}"
	UrlTokenBrand             = "{brand}"
	UrlTokenModel             = "{model}"
	UrlTokenBrowser           = "{browser}"
	UrlTokenBrowserVersion    = "{browserversion}"
	UrlTokenOS                = "{os}"
	UrlTokenOSVersion         = "{osversion}"
	UrlTokenCountry           = "{country}"
	UrlTokenCountryName       = "{countryname}"
	UrlTokenCity              = "{city}"
	UrlTokenRegion            = "{region}"
	UrlTokenIsp               = "{isp}"
	UrlTokenIp                = "{ip}"
	UrlTokenUserAgent         = "{useragent}"
	UrlTokenTrackingDomain    = "{trackingdomain}"
	UrlTokenReferrerDomain    = "{referrerdomain}"
	UrlTokenCarrier           = "{carrier}"
	UrlTokenConnectionType    = "{connection.type}"
	UrlTokenVar1              = "{var1}"
	UrlTokenVar2              = "{var2}"
	UrlTokenVar3              = "{var3}"
	UrlTokenVar4              = "{var4}"
	UrlTokenVar5              = "{var5}"
	UrlTokenVar6              = "{var6}"
	UrlTokenVar7              = "{var7}"
	UrlTokenVar8              = "{var8}"
	UrlTokenVar9              = "{var9}"
	UrlTokenVar10             = "{var10}"
)
