
CREATE TABLE `AdConversionsStatis` (
  `id` bigint(22) NOT NULL AUTO_INCREMENT,
  `UserID` int(11) DEFAULT NULL COMMENT '用户ID',
  `PostbackTimestamp` bigint(22) DEFAULT NULL COMMENT 'unix时间戳，精确到秒',
  `VisitTimestamp` bigint(22) DEFAULT NULL COMMENT 'unix时间戳，精确到秒',
  `ExternalID` varchar(48) DEFAULT '' COMMENT 'External ID',
  `ClickID` varchar(36) DEFAULT '' COMMENT 'ClickID',
  `TransactionID` varchar(40) DEFAULT 'Unknown' COMMENT 'Transaction ID',
  `Revenue` double DEFAULT '0',
  `Cost` double DEFAULT '0',
  `CampaignName` varchar(64) DEFAULT '' COMMENT 'Campaign Name',
  `CampaignID` int(11) DEFAULT '0' COMMENT 'Campaign ID',
  `LanderName` varchar(64) DEFAULT '' COMMENT 'Lander Name',
  `LanderID` int(11) DEFAULT '0' COMMENT 'Lander ID',
  `OfferName` varchar(64) DEFAULT '' COMMENT 'Offer Name',
  `OfferID` int(11) DEFAULT '0' COMMENT 'Offer ID',
  `Country` varchar(40) DEFAULT '' COMMENT 'Country',
  `CountryCode` varchar(2) DEFAULT '' COMMENT 'Country Code like CA',
  `TrafficSourceName` varchar(255) DEFAULT '' COMMENT 'Traffic Source Name',
  `TrafficSourceID` int(11) DEFAULT '0' COMMENT 'Traffic Source ID',
  `AffiliateNetworkName` varchar(255) DEFAULT '' COMMENT 'Affiliate Network Name',
  `AffiliateNetworkID` int(11) DEFAULT '0' COMMENT 'Affiliate Network ID',
  `Device` varchar(16) DEFAULT 'Unknown' COMMENT 'Device Type',
  `OS` varchar(16) DEFAULT '' COMMENT 'Operating System',
  `OSVersion` varchar(32) DEFAULT '' COMMENT 'Operating System Version',
  `Brand` varchar(32) DEFAULT NULL COMMENT '设备品牌，如Samsung',
  `Model` varchar(45) DEFAULT NULL COMMENT '手机型号，如Samsung Galaxy S4',
  `Browser` varchar(32) DEFAULT NULL COMMENT '浏览器，如Chrome Mobile',
  `BrowserVersion` varchar(64) DEFAULT NULL COMMENT '浏览器版本号，如Chrome Mobile 55',
  `ISP` varchar(64) DEFAULT NULL COMMENT 'ISP或者Carrier，互联网服务提供商，如Bell Canada',
  `MobileCarrier` varchar(64) DEFAULT NULL COMMENT '移动运营商',
  `ConnectionType` varchar(16) DEFAULT NULL COMMENT '网络连接类型，Broadband, Cable, Xdsl, Mobile, Satellite',
  `VisitorIP` varchar(16) DEFAULT '' COMMENT 'Visitor IP, 如158.69.104.15',
  `VisitorReferrer` varchar(255) DEFAULT '' COMMENT 'Visitor Referrer, 如http://prestoris.com/afu.php?zoneid=478410',
  `V1` varchar(255) DEFAULT '',
  `V2` varchar(255) DEFAULT '',
  `V3` varchar(255) DEFAULT '',
  `V4` varchar(255) DEFAULT '',
  `V5` varchar(255) DEFAULT '',
  `V6` varchar(255) DEFAULT '',
  `V7` varchar(255) DEFAULT '',
  `V8` varchar(255) DEFAULT '',
  `V9` varchar(255) DEFAULT '',
  `V10` varchar(255) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `IndexPostbackTimestamp` (`PostbackTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=200001 DEFAULT CHARSET=utf8;



CREATE TABLE `AdIPStatis` (
  `UserID` int(11) DEFAULT NULL COMMENT '用户ID',
  `Timestamp` bigint(22) DEFAULT NULL COMMENT 'unix时间戳，精确到小时，如1483869600',
  `CampaignID` int(11) DEFAULT NULL COMMENT 'Campaign的ID',
  `IP` varchar(16) DEFAULT NULL COMMENT 'IP地址',
  `Visits` int(11) DEFAULT '0' COMMENT '累计的展示次数',
  `Clicks` int(11) DEFAULT '0' COMMENT '累计的点击次数',
  `Conversions` int(11) DEFAULT '0' COMMENT '累计的成功转换次数',
  `Cost` bigint(20) DEFAULT '0' COMMENT '累计的开销(实际的值x1000000)',
  `Revenue` bigint(20) DEFAULT '0' COMMENT '累计的收益(实际的值x1000000)',
  `Impressions` int(11) DEFAULT '0',
  UNIQUE KEY `unique_key` (`UserID`,`Timestamp`,`CampaignID`,`IP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `AdReferrerStatis` (
  `UserID` int(11) DEFAULT NULL COMMENT '用户ID',
  `Timestamp` bigint(22) DEFAULT NULL,
  `CampaignID` int(11) DEFAULT NULL COMMENT 'Campaign的ID',
  `Referrer` varchar(255) DEFAULT 'Unknown' COMMENT 'Referrer URL',
  `Visits` int(11) DEFAULT '0' COMMENT '累计的展示次数',
  `Clicks` int(11) DEFAULT '0' COMMENT '累计的点击次数',
  `Conversions` int(11) DEFAULT '0' COMMENT '累计的成功转换次数',
  `Cost` bigint(20) DEFAULT '0' COMMENT '累计的开销(实际的值x1000000)',
  `Revenue` bigint(20) DEFAULT '0' COMMENT '累计的收益(实际的值x1000000)',
  `Impressions` int(11) DEFAULT '0',
  UNIQUE KEY `unique_key` (`UserID`,`Timestamp`,`CampaignID`,`Referrer`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `AdReferrerDomainStatis` (
  `UserID` int(11) DEFAULT NULL COMMENT '用户ID',
  `Timestamp` bigint(22) DEFAULT NULL,
  `CampaignID` int(11) DEFAULT NULL COMMENT 'Campaign的ID',
  `ReferrerDomain` varchar(255) DEFAULT 'Unknown' COMMENT 'Referrer URL',
  `Visits` int(11) DEFAULT '0' COMMENT '累计的展示次数',
  `Clicks` int(11) DEFAULT '0' COMMENT '累计的点击次数',
  `Conversions` int(11) DEFAULT '0' COMMENT '累计的成功转换次数',
  `Cost` bigint(20) DEFAULT '0' COMMENT '累计的开销(实际的值x1000000)',
  `Revenue` bigint(20) DEFAULT '0' COMMENT '累计的收益(实际的值x1000000)',
  `Impressions` int(11) DEFAULT '0',
  UNIQUE KEY `unique_key` (`UserID`,`Timestamp`,`CampaignID`,`ReferrerDomain`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `AdStatis` (
  `UserID` int(11) DEFAULT NULL COMMENT '用户ID',
  `CampaignID` int(11) DEFAULT NULL COMMENT 'Campaign的ID',
  `FlowID` int(11) DEFAULT NULL COMMENT 'Flow的ID',
  `LanderID` int(11) DEFAULT NULL COMMENT 'Lander的ID',
  `OfferID` int(11) DEFAULT NULL COMMENT 'Offer的ID',
  `AffiliateNetworkID` int(11) NOT NULL DEFAULT '0',
  `TrafficSourceID` int(11) DEFAULT NULL COMMENT 'TrafficSource的ID',
  `Language` varchar(20) DEFAULT NULL COMMENT '语言，如：English',
  `Model` varchar(45) DEFAULT NULL COMMENT '手机型号，如Samsung Galaxy S4',
  `Country` varchar(40) DEFAULT NULL COMMENT '国家，如Canada',
  `City` varchar(45) DEFAULT NULL COMMENT '城市，如Toronto',
  `Region` varchar(45) DEFAULT NULL COMMENT '地区，如California',
  `ISP` varchar(64) DEFAULT NULL COMMENT 'ISP或者Carrier，互联网服务提供商，如Bell Canada',
  `MobileCarrier` varchar(64) DEFAULT NULL COMMENT '移动运营商',
  `Domain` varchar(45) DEFAULT NULL COMMENT 'Referer Domain，如onclkds.com',
  `DeviceType` varchar(16) DEFAULT '' COMMENT 'Mobile Phone, Desktop, Unknown, Tablet',
  `Brand` varchar(32) DEFAULT NULL COMMENT '设备品牌，如Samsung',
  `OS` varchar(16) DEFAULT NULL COMMENT '系统类型，如',
  `OSVersion` varchar(32) DEFAULT NULL COMMENT '系统版本号，如Android 6.0',
  `Browser` varchar(32) DEFAULT NULL COMMENT '浏览器，如Chrome Mobile',
  `BrowserVersion` varchar(64) DEFAULT NULL COMMENT '浏览器版本号，如Chrome Mobile 55',
  `ConnectionType` varchar(16) DEFAULT NULL COMMENT '网络连接类型，Broadband, Cable, Xdsl, Mobile, Satellite',
  `Timestamp` bigint(22) DEFAULT NULL COMMENT 'unix时间戳，精确到小时，如1483869600',
  `Visits` int(11) DEFAULT '0' COMMENT '累计的展示次数',
  `Clicks` int(11) DEFAULT '0' COMMENT '累计的点击次数',
  `Conversions` int(11) DEFAULT '0' COMMENT '累计的成功转换次数',
  `Cost` bigint(20) DEFAULT '0' COMMENT '累计的开销(实际的值x1000000)',
  `Revenue` bigint(20) DEFAULT '0' COMMENT '累计的收益(实际的值x1000000)',
  `Impressions` int(11) DEFAULT '0',
  `KeysMD5` char(32) DEFAULT NULL COMMENT '`UserID`, `CampaignID`, `FlowID`, `LanderID`, `OfferID`, `TrafficSourceID`, `Language`, `Model`, `Country`, `City`, `Region`, `ISP`, `Domain`, `Brand`, `OS`, `OSVersion`, `Brower`, `BrowerVersion`, `ConnectionType`, `Timestamp` 这些字段用,拼接到一块儿之后算出来的MD5',
  `V1` varchar(255) DEFAULT '0',
  `V2` varchar(255) DEFAULT '0',
  `V3` varchar(255) DEFAULT '0',
  `V4` varchar(255) DEFAULT '0',
  `V5` varchar(255) DEFAULT '0',
  `V6` varchar(255) DEFAULT '0',
  `V7` varchar(255) DEFAULT '0',
  `V8` varchar(255) DEFAULT '0',
  `V9` varchar(255) DEFAULT '0',
  `V10` varchar(255) DEFAULT '0',
  UNIQUE KEY `md5_unique_key` (`KeysMD5`),
  KEY `index_for_select` (`UserID`,`Timestamp`,`CampaignID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

